// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTransfCtrl.proto

package dms;

public final class MTransfCtrlOuterClass {
  private MTransfCtrlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MTransfCtrlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dms.MTransfCtrl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     * @return Whether the msgtype field is set.
     */
    boolean hasMsgtype();
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     * @return The msgtype.
     */
    int getMsgtype();

    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     * @return Whether the sysType field is set.
     */
    boolean hasSysType();
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     * @return The sysType.
     */
    int getSysType();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return Whether the fromAppID field is set.
     */
    boolean hasFromAppID();
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return The fromAppID.
     */
    java.lang.String getFromAppID();
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return The bytes for fromAppID.
     */
    com.google.protobuf.ByteString
        getFromAppIDBytes();

    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return Whether the msgName field is set.
     */
    boolean hasMsgName();
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return The msgName.
     */
    java.lang.String getMsgName();
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return The bytes for msgName.
     */
    com.google.protobuf.ByteString
        getMsgNameBytes();

    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code dms.MTransfCtrl}
   */
  public static final class MTransfCtrl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dms.MTransfCtrl)
      MTransfCtrlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MTransfCtrl.newBuilder() to construct.
    private MTransfCtrl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MTransfCtrl() {
      timestamp_ = "";
      fromAppID_ = "";
      msgName_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MTransfCtrl();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dms.MTransfCtrlOuterClass.MTransfCtrl.class, dms.MTransfCtrlOuterClass.MTransfCtrl.Builder.class);
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgtype_;
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     * @return Whether the msgtype field is set.
     */
    @java.lang.Override
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     * @return The msgtype.
     */
    @java.lang.Override
    public int getMsgtype() {
      return msgtype_;
    }

    public static final int SYSTYPE_FIELD_NUMBER = 2;
    private int sysType_;
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     * @return Whether the sysType field is set.
     */
    @java.lang.Override
    public boolean hasSysType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     * @return The sysType.
     */
    @java.lang.Override
    public int getSysType() {
      return sysType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMAPPID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromAppID_;
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return Whether the fromAppID field is set.
     */
    @java.lang.Override
    public boolean hasFromAppID() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return The fromAppID.
     */
    @java.lang.Override
    public java.lang.String getFromAppID() {
      java.lang.Object ref = fromAppID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAppID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     * @return The bytes for fromAppID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromAppIDBytes() {
      java.lang.Object ref = fromAppID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAppID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object msgName_;
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return Whether the msgName field is set.
     */
    @java.lang.Override
    public boolean hasMsgName() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return The msgName.
     */
    @java.lang.Override
    public java.lang.String getMsgName() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     * @return The bytes for msgName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, sysType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromAppID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgName_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sysType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromAppID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgName_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dms.MTransfCtrlOuterClass.MTransfCtrl)) {
        return super.equals(obj);
      }
      dms.MTransfCtrlOuterClass.MTransfCtrl other = (dms.MTransfCtrlOuterClass.MTransfCtrl) obj;

      if (hasMsgtype() != other.hasMsgtype()) return false;
      if (hasMsgtype()) {
        if (getMsgtype()
            != other.getMsgtype()) return false;
      }
      if (hasSysType() != other.hasSysType()) return false;
      if (hasSysType()) {
        if (getSysType()
            != other.getSysType()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasFromAppID() != other.hasFromAppID()) return false;
      if (hasFromAppID()) {
        if (!getFromAppID()
            .equals(other.getFromAppID())) return false;
      }
      if (hasMsgName() != other.hasMsgName()) return false;
      if (hasMsgName()) {
        if (!getMsgName()
            .equals(other.getMsgName())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgtype()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgtype();
      }
      if (hasSysType()) {
        hash = (37 * hash) + SYSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSysType();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasFromAppID()) {
        hash = (37 * hash) + FROMAPPID_FIELD_NUMBER;
        hash = (53 * hash) + getFromAppID().hashCode();
      }
      if (hasMsgName()) {
        hash = (37 * hash) + MSGNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMsgName().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dms.MTransfCtrlOuterClass.MTransfCtrl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dms.MTransfCtrl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dms.MTransfCtrl)
        dms.MTransfCtrlOuterClass.MTransfCtrlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dms.MTransfCtrlOuterClass.MTransfCtrl.class, dms.MTransfCtrlOuterClass.MTransfCtrl.Builder.class);
      }

      // Construct using dms.MTransfCtrlOuterClass.MTransfCtrl.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sysType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fromAppID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
      }

      @java.lang.Override
      public dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstanceForType() {
        return dms.MTransfCtrlOuterClass.MTransfCtrl.getDefaultInstance();
      }

      @java.lang.Override
      public dms.MTransfCtrlOuterClass.MTransfCtrl build() {
        dms.MTransfCtrlOuterClass.MTransfCtrl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dms.MTransfCtrlOuterClass.MTransfCtrl buildPartial() {
        dms.MTransfCtrlOuterClass.MTransfCtrl result = new dms.MTransfCtrlOuterClass.MTransfCtrl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgtype_ = msgtype_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sysType_ = sysType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromAppID_ = fromAppID_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgName_ = msgName_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dms.MTransfCtrlOuterClass.MTransfCtrl) {
          return mergeFrom((dms.MTransfCtrlOuterClass.MTransfCtrl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dms.MTransfCtrlOuterClass.MTransfCtrl other) {
        if (other == dms.MTransfCtrlOuterClass.MTransfCtrl.getDefaultInstance()) return this;
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasSysType()) {
          setSysType(other.getSysType());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000004;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasFromAppID()) {
          bitField0_ |= 0x00000008;
          fromAppID_ = other.fromAppID_;
          onChanged();
        }
        if (other.hasMsgName()) {
          bitField0_ |= 0x00000010;
          msgName_ = other.msgName_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                msgtype_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                sysType_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                timestamp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                fromAppID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                msgName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int msgtype_ ;
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       * @return Whether the msgtype field is set.
       */
      @java.lang.Override
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       * @return The msgtype.
       */
      @java.lang.Override
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       * @param value The msgtype to set.
       * @return This builder for chaining.
       */
      public Builder setMsgtype(int value) {
        bitField0_ |= 0x00000001;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = 0;
        onChanged();
        return this;
      }

      private int sysType_ ;
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       * @return Whether the sysType field is set.
       */
      @java.lang.Override
      public boolean hasSysType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       * @return The sysType.
       */
      @java.lang.Override
      public int getSysType() {
        return sysType_;
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       * @param value The sysType to set.
       * @return This builder for chaining.
       */
      public Builder setSysType(int value) {
        bitField0_ |= 0x00000002;
        sysType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSysType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sysType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromAppID_ = "";
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @return Whether the fromAppID field is set.
       */
      public boolean hasFromAppID() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @return The fromAppID.
       */
      public java.lang.String getFromAppID() {
        java.lang.Object ref = fromAppID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAppID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @return The bytes for fromAppID.
       */
      public com.google.protobuf.ByteString
          getFromAppIDBytes() {
        java.lang.Object ref = fromAppID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAppID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @param value The fromAppID to set.
       * @return This builder for chaining.
       */
      public Builder setFromAppID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromAppID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromAppID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromAppID_ = getDefaultInstance().getFromAppID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       * @param value The bytes for fromAppID to set.
       * @return This builder for chaining.
       */
      public Builder setFromAppIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        fromAppID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgName_ = "";
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @return Whether the msgName field is set.
       */
      public boolean hasMsgName() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @return The msgName.
       */
      public java.lang.String getMsgName() {
        java.lang.Object ref = msgName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @return The bytes for msgName.
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        java.lang.Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @param value The msgName to set.
       * @return This builder for chaining.
       */
      public Builder setMsgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgName_ = getDefaultInstance().getMsgName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       * @param value The bytes for msgName to set.
       * @return This builder for chaining.
       */
      public Builder setMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        msgName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       * @return Whether the data field is set.
       */
      @java.lang.Override
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dms.MTransfCtrl)
    }

    // @@protoc_insertion_point(class_scope:dms.MTransfCtrl)
    private static final dms.MTransfCtrlOuterClass.MTransfCtrl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dms.MTransfCtrlOuterClass.MTransfCtrl();
    }

    public static dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MTransfCtrl>
        PARSER = new com.google.protobuf.AbstractParser<MTransfCtrl>() {
      @java.lang.Override
      public MTransfCtrl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MTransfCtrl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MTransfCtrl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dms_MTransfCtrl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dms_MTransfCtrl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MTransfCtrl.proto\022\003dms\"\333\001\n\013MTransfCtrl" +
      "\022\024\n\007Msgtype\030\001 \001(\005H\000\210\001\001\022\024\n\007SysType\030\002 \001(\rH" +
      "\001\210\001\001\022\026\n\tTimestamp\030\003 \001(\tH\002\210\001\001\022\026\n\tFromAppI" +
      "D\030\004 \001(\tH\003\210\001\001\022\024\n\007MsgName\030\005 \001(\tH\004\210\001\001\022\021\n\004da" +
      "ta\030\006 \001(\014H\005\210\001\001B\n\n\010_MsgtypeB\n\n\010_SysTypeB\014\n" +
      "\n_TimestampB\014\n\n_FromAppIDB\n\n\010_MsgNameB\007\n" +
      "\005_datab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dms_MTransfCtrl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dms_MTransfCtrl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dms_MTransfCtrl_descriptor,
        new java.lang.String[] { "Msgtype", "SysType", "Timestamp", "FromAppID", "MsgName", "Data", "Msgtype", "SysType", "Timestamp", "FromAppID", "MsgName", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
